apiVersion: management.loft.sh/v1
kind: App
metadata:
  name: argocd
spec:
  displayName: ArgoCD
  description: Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes
  recommendedApp:
    - cluster
  defaultNamespace: argocd
  icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
  config:
    chart:
      name: argo-cd
      version: 7.3.6
      repoURL: https://argoproj.github.io/argo-helm
    values: '{{ .Values.appValues }}'
  parameters:
    - variable: appValues
      label: Helm Values
      description: The helm values to use to deploy this chart.
      type: multiline
      defaultValue: |-
        server:
          ingress:
            enabled: true
            hosts:
            - my-domain.com
  access:
    - verbs:
        - get
      users:
        - '*'
