name: delete-old-repo-package

# on merge to main from pull request (recommended)
on:
  create
jobs:
  delete-old-repo-package:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      packages: admin
    steps:
      - id: delete package
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.generate-githubapp-token.outputs.token }}
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/loft-demos/packages/container/${{ github.event.repository.name }}
